// MUST stay structurally compatible with `SonosActivityAttributes.ContentState`
// in the iOS app (Shared/Models.swift). Apple's ActivityKit decodes the
// `content-state` JSON of an APNs liveactivity push using the iOS-side
// Codable shape, so any field name / type mismatch will silently fail to
// decode and the Live Activity won't update.
//
// Date fields use Apple's `.deferredToDate` JSONDecoder default which
// expects seconds since 2001-01-01 UTC (NSDate reference date), not Unix
// epoch. Convert with `toSwiftDate()` in apns.ts before sending.
export interface LiveActivityContentState {
  trackTitle: string;
  artist: string;
  album: string;
  isPlaying: boolean;
  positionSeconds: number;
  durationSeconds: number;

  // Optional fields — keys must remain optional in the same way iOS does
  // them, but JSON-omit when undefined so we don't ship explicit nulls
  // that confuse the Swift decoder.
  dominantColorHex?: string | null;
  startedAt?: number | null;        // Swift Date, seconds since 2001-01-01 UTC
  endsAt?: number | null;           // Swift Date, seconds since 2001-01-01 UTC
  albumArtThumbnail?: string | null; // base64 (Swift Data ↔ JSON)
  artworkTraceId?: string | null;    // diagnostic-only id for correlating artwork logs
  groupMemberCount: number;
  playbackSourceRaw?: string | null;
  soundbarNightMode?: boolean | null;
  soundbarSpeechEnhancementRawLevel?: number | null;
  liveActivityStyleRaw?: string | null;
  audioQualityLabel?: string | null;
}

export interface SonosGroupMemberSnapshot {
  /// Stable Sonos UUID when available, otherwise the member LAN address.
  id: string;
  name: string;
  host: string;
  isCoordinator: boolean;
  /// Individual RenderingControl volume. Null when the member does not expose
  /// a readable volume endpoint.
  volume?: number | null;
}

/// Structured track quality reported by Sonos Local Control. Keep the display
/// label for backwards compatibility, but clients should prefer these raw
/// fields so a relay refresh cannot collapse Hi-Res metadata to a string.
export interface SonosAudioQualitySnapshot {
  label?: string | null;
  serviceName?: string | null;
  lossless?: boolean | null;
  immersive?: boolean | null;
  bitDepth?: number | null;
  sampleRate?: number | null;
}

/// Minimal projection of what we keep in memory per Sonos coordinator. Built
/// from sonos-ts AVTransport / RenderingControl events.
export interface SonosGroupSnapshot {
  groupId: string;
  speakerName: string;
  trackTitle: string;
  artist: string;
  album: string;
  /// Raw Sonos transport URI. The dashboard uses Apple Music catalog IDs
  /// embedded in this value to resolve exact animated album artwork.
  trackUri?: string | null;
  albumArtUri?: string | null;
  albumArtFallbackUri?: string | null;
  isPlaying: boolean;
  /// Full Sonos AVTransport state. `isPlaying` remains for backwards
  /// compatibility, while clients that care about paused/stopped/transitioning
  /// can preserve the richer state.
  transportStateRaw?: string | null;
  /// Group volume sampled from GroupRenderingControl. Optional for older
  /// persisted/test snapshots and null when the coordinator does not expose it.
  groupVolume?: number | null;
  playbackSourceRaw?: string | null;
  /// Raw DeviceProperties.GetZoneInfo HTAudioIn value for TV playback.
  /// Kept so clients can preserve unknown formats instead of relying on a
  /// lossy display label.
  tvAudioFormatRawCode?: number | null;
  /// Full Sonos TV audio format label before it is compacted for display.
  /// Examples: "Dolby Atmos (MAT 2.0)" and "PCM 2.0 no audio".
  tvAudioFormatLabel?: string | null;
  /// Whether HTAudioIn reports an active TV audio signal. This deliberately
  /// differs from `isPlaying`, which reflects AVTransport state and may stay
  /// PLAYING while HDMI/eARC is silent.
  tvHasSignal?: boolean | null;
  soundbarNightMode?: boolean | null;
  soundbarSpeechEnhancementRawLevel?: number | null;
  liveActivityStyleRaw?: string | null;
  audioQualityLabel?: string | null;
  audioQuality?: SonosAudioQualitySnapshot | null;
  musicAmbienceEligible?: boolean;
  positionSeconds: number;
  durationSeconds: number;
  groupMemberCount: number;
  /// Visible rooms only. Bonded surrounds, stereo partners and Subs are
  /// intentionally excluded to match the iOS Home-card topology.
  groupMembers?: SonosGroupMemberSnapshot[];
  /// Wall-clock time at which `positionSeconds` was sampled. Used to derive
  /// the Swift-encoded `startedAt` / `endsAt` for the progress timer.
  sampledAt: Date;
}

export interface RegisterRequest {
    groupId: string;
  /// Hex string from `Activity.pushTokenUpdates` on iOS.
  token: string;
  /// Stable per-install identifier generated by the iOS app.
  clientId?: string;
  /// ActivityKit activity id. Used to replace rotated tokens for the same
  /// visible Live Activity instead of accumulating dead tokens forever.
  activityId?: string;
  /// App-owned Live Activity presentation preference. Playback metadata and
  /// audio quality are owned by the relay snapshot pipeline.
  liveActivityStyleRaw?: string | null;
  /// Speaker name carried by `SonosActivityAttributes.speakerName` on iOS.
  /// We log it but the Live Activity itself is created on-device with the
  /// attributes — push updates only carry ContentState, not Attributes.
  attributes?: { speakerName?: string };
}

export interface TokenEntry extends RegisterRequest {
  /// ISO timestamp of registration; mostly for log auditing.
  registeredAt: string;
  /// Hash of the last ContentState we successfully shipped. Used to skip
  /// no-op pushes (e.g. positionSeconds drifting by 1 doesn't count).
  lastSentHash?: string;
}

export interface PushToStartRegisterRequest {
  groupId: string;
  token: string;
  clientId?: string;
  speakerName?: string;
  liveActivityStyleRaw?: string | null;
  activeActivityIds?: string[];
  clearDismissalSuppression?: boolean;
}

export interface PushToStartTokenEntry extends PushToStartRegisterRequest {
  registeredAt: string;
  lastStartAt?: string;
  startAttemptCount?: number;
}

export interface LiveActivityDismissedRequest {
  groupId: string;
  clientId?: string;
  activityId?: string;
  token?: string;
  suppressForSeconds?: number;
}

export interface PushToStartSuppressionEntry {
  groupId: string;
  clientId?: string;
  activityId?: string;
  reason: 'user-dismissed';
  recordedAt: string;
  suppressUntil: string;
}

export interface LiveActivityStartAttributes {
  speakerName: string;
  groupId?: string | null;
}

export type NowPlayingTokenKind = 'start' | 'update';

export interface NowPlayingRegisterRequest {
  kind: NowPlayingTokenKind;
  groupId: string;
  token: string;
  sessionId: string;
  sessionGeneration?: string;
  clientId: string;
  speakerName: string;
  relayURLString: string;
  requestStart?: boolean;
}

export interface NowPlayingTokenEntry extends NowPlayingRegisterRequest {
  registeredAt: string;
  lastSentHash?: string;
}

// Must match RemoteMediaSessionShared/SonosRemoteMediaSessionAttributes.swift.
export interface NowPlayingAttributes {
  id: string;
  sessionGeneration?: string | null;
  groupID: string;
  speakerName: string;
  devices?: Array<{
    id: string;
    name: string;
    host?: string | null;
    volume?: number | null;
  }>;
  trackID: string;
  title: string;
  artist: string;
  album: string;
  artworkURLString?: string | null;
  artworkFallbackURLString?: string | null;
  animatedArtworkURLString?: string | null;
  playbackSourceRaw?: string | null;
  isLiveStream: boolean;
  isPlaying: boolean;
  elapsedTime: number;
  duration: number;
  timestamp: number;
  volume: number;
  clientID: string;
  relayURLString?: string | null;
  relayCommandToken?: string | null;
}
